version: "3"
services:
  app:
    build: .
    user: "node"
    environment:
      - NODE_ENV=production
    volumes:
      - ./images:/app/images
    expose:
      - "5000"
    ports:
      - 5000:5000
